### ISSUE TITLE
a lot of stuff that is bugged or doesnt have sprites

### ISSUE THREAD

**Issue by uujuju1** [vinhsad/Project-Scrap#9]
crate icon sprite doesnt have the yellow stuff
you forgot to make the bottom sprite for the heat generator
tungsten doesnt have proper name
why dirty water doesnt have a sprite
some other stuff doesnt have sprites(i may or may not make a pull request about it)
desciption in paradox
descirption in current
put description to Steam

**Comment by vinhsad** [comment]
Mass Fixing Time
